In [1]:
print("sgk")

sgk


In [2]:
print("8 "*8)

8 8 8 8 8 8 8 8 


In [3]:
n=8
for i in range(1,n):
    print(i*i,end=' ')


1 4 9 16 25 36 49 

In [4]:
n=int(input())
for i in range(n):
    for j in range(1,i+1):
        print(j*i,end=' ')
    print()

5

1 
2 4 
3 6 9 
4 8 12 16 


# Python

# ###### Python

In [5]:
n=int(input())
for i in range(n):
    for j in range(1,i+1):
        print(j*(i+1),end=' ')
    print()

5

2 
3 6 
4 8 12 
5 10 15 20 


# ESC+M 

In [6]:
import numpy as np


In [7]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [8]:
d1=np.array([45,76,89,7,8,8,8,3,2,1,4])

In [9]:
d1.shape

(11,)

In [10]:
d1.shape

(11,)

In [11]:
print(d1)

[45 76 89  7  8  8  8  3  2  1  4]


In [12]:
d1.size



11

In [13]:
d1.ndim

1

In [14]:
d1[0]

45

In [15]:
d1[2]

89

In [16]:
d1[1]

76

In [17]:
d1[1:3]

array([76, 89])

In [18]:
d1[0:2]

array([45, 76])

In [19]:
data=np.array(["Range",123,'CSE',"A",45.25])

In [20]:
data

array(['Range', '123', 'CSE', 'A', '45.25'], dtype='<U5')

In [21]:
import time
start_time=time.time()
i=0
list1=[x for x in range(1,100000)]
list2=[y for y in range(1,100000)]
while(i<len(list1)):
    #print(list1[i]*list2[i],end=' ')
    i+=1
end_time=time.time()
print(end_time-start_time)


0.03124523162841797


In [22]:
import time
start_time=time.time()
i=0
list1=[x for x in range(1,100000)]
list2=[y for y in range(1,100000)]
op=list(map(lambda x,y:x*y,list1,list2))
end_time=time.time()
print(end_time-start_time)


0.015624046325683594


In [23]:
import time
start_time1=time.time()
ar1=np.array(list1)
ar2=np.array(list2)
ar1*ar2
end_time1=time.time()
print(end_time1-start_time1)

0.015609502792358398


In [24]:
d2=np.array([[45,74,36],[96,78,69],[14,25,63]])

In [25]:
d2.ndim

2

In [26]:
d2.size

9

In [27]:
d2

array([[45, 74, 36],
       [96, 78, 69],
       [14, 25, 63]])

In [28]:
d2[0]

array([45, 74, 36])

In [29]:
d2[0][0]

45

In [30]:
d2[2][0]

14

In [31]:
d2[1][3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [ ]:
d2[1][2]

In [ ]:
d2[0][2]

In [ ]:
d2[0,2]

In [ ]:
np.max(d2[1])

In [ ]:
d2[:,2]

In [ ]:
d2[:,1].max()

In [ ]:
d2[:,1].min()

In [ ]:
for i in range(len(d2)):
    print(sum(d2[i]))

In [ ]:
d2.sum(axis=0)

In [ ]:
d2.sum(axis=1)

In [ ]:
d3=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])

In [ ]:
d3

In [ ]:
d3.ndim

In [ ]:
255*125*3

### 

In [ ]:
d3[0,0]

In [ ]:
d3[0]

In [ ]:
d3[0,0,0]

# Arange()

In [ ]:
for i in range(10):
    print(i,end=' ')
for i in arange(10):
    print(i,end=' ')

In [ ]:
import numpy as np
for i in range(10):
    print(i,end=' ')
for i in arange(10):
    print(i,end=' ')

In [ ]:
for i in range(1,11):
    print(i,end=' ')
print()
for i in np.arange(1,11,2):
    print(i,end=' ')

In [ ]:
for i in range(1,6,1):
    print(i,end=' ')
print()
for i in np.arange(1,6,0.5):
    print(i,end=' ')

In [ ]:
np.linspace(1,10,20)

# zeos matrix

In [ ]:
print(np.zeros([10,20]))

In [ ]:
np.ones([5,6])

In [ ]:
np.eye(5,5)

In [ ]:
np.tile(10,[5,5])

In [ ]:
d21=np.array([[14,25,36,41,52],[24,51,35,15,16]])

In [ ]:
d21

In [ ]:
d21.ndim

In [ ]:
add_marks=np.tile(5,[2,5])

In [ ]:
add_marks

In [ ]:
total_marks=d21+add_marks

In [ ]:
total_marks

In [ ]:
asha =np.array([[1,10,20],[2,20,30],[3,45,55]])

In [ ]:
asha

In [ ]:
np.linalg.inv(asha)

# Random

In [ ]:
np.random.random(10)

In [ ]:
np.random.random(100)

In [ ]:
np.random.randint(1,100,5)

In [ ]:
np.random.rand(10)

In [ ]:
np.arange(1,26).reshape(5,5)

In [ ]:
np.arange(1,49).reshape(4,3,4)

In [ ]:
np.arange(1,37).reshape(2,2,3,3)

In [32]:
np.sin(90)

0.8939966636005579

In [33]:
sin(0)

NameError: name 'sin' is not defined

In [34]:
np.sin(0)

0.0

In [35]:
np.cos(180)

-0.5984600690578582

In [36]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [37]:
tan(45)

NameError: name 'tan' is not defined

In [38]:
np.tan(45)

1.6197751905438615

In [39]:
np.sinh(10)

11013.232874703393

In [40]:
np.arcsin(1)

1.5707963267948966

In [41]:
np.arcsin(0)

0.0

In [42]:
np.arcsin(90)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in arcsin
  """Entry point for launching an IPython kernel.


nan

In [43]:
array=np.arange(1,10).reshape(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
array.max()

9

In [45]:
array.min()

1

In [46]:
array.argmax() # It return the position of max element

8

In [47]:
array.argmin()# It return the lowest element position

0

In [48]:
sec1=np.array(np.random.randint(10,20,[4,4]))
sec1

array([[12, 14, 18, 17],
       [14, 12, 13, 11],
       [13, 19, 17, 14],
       [17, 16, 17, 16]])

In [49]:
sec2=np.array(np.random.randint(1,10,[4,4]))

In [50]:
sec2

array([[6, 1, 3, 9],
       [4, 8, 8, 5],
       [1, 7, 8, 9],
       [4, 7, 4, 7]])

In [52]:
np.vstack((sec1,sec2)) #It combins the two matrices(V santds for vertical)

array([[12, 14, 18, 17],
       [14, 12, 13, 11],
       [13, 19, 17, 14],
       [17, 16, 17, 16],
       [ 6,  1,  3,  9],
       [ 4,  8,  8,  5],
       [ 1,  7,  8,  9],
       [ 4,  7,  4,  7]])

In [53]:
np.hstack(sec1,sec2)

TypeError: hstack() takes 1 positional argument but 2 were given

In [54]:
np.hstack((sec1,sec2))# h stands for horizontal

array([[12, 14, 18, 17,  6,  1,  3,  9],
       [14, 12, 13, 11,  4,  8,  8,  5],
       [13, 19, 17, 14,  1,  7,  8,  9],
       [17, 16, 17, 16,  4,  7,  4,  7]])

In [55]:
np.column_stack((sec1,sec2))

array([[12, 14, 18, 17,  6,  1,  3,  9],
       [14, 12, 13, 11,  4,  8,  8,  5],
       [13, 19, 17, 14,  1,  7,  8,  9],
       [17, 16, 17, 16,  4,  7,  4,  7]])

In [56]:
sec1*sec2


array([[ 72,  14,  54, 153],
       [ 56,  96, 104,  55],
       [ 13, 133, 136, 126],
       [ 68, 112,  68, 112]])

In [57]:
sec1.dot(sec2)

array([[214, 369, 360, 459],
       [189, 278, 286, 380],
       [227, 382, 383, 463],
       [247, 376, 379, 498]])

In [58]:
sec1@sec2

array([[214, 369, 360, 459],
       [189, 278, 286, 380],
       [227, 382, 383, 463],
       [247, 376, 379, 498]])

In [60]:
sec1.transpose()

array([[12, 14, 13, 17],
       [14, 12, 19, 16],
       [18, 13, 17, 17],
       [17, 11, 14, 16]])

In [61]:
sec1.trace()

57

In [62]:
np.hsplit(sec1,2)

[array([[12, 14],
        [14, 12],
        [13, 19],
        [17, 16]]), array([[18, 17],
        [13, 11],
        [17, 14],
        [17, 16]])]

In [63]:
np.abs(100.25)

100.25

In [64]:
np.abs(-1)

1

In [66]:
np.all(sec1<=10)

False

In [67]:
np.any(sec1<0)

False

In [68]:
np.round(12.36)

12.0

In [69]:
n.round(12.63)

AttributeError: 'int' object has no attribute 'round'

In [70]:
np.round(12.63)

13.0